apiVersion: v1
kind: Service
metadata:
  name: {{ include "bee-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bee-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "bee-web.selectorLabels" . | nindent 4 }}
