apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.domain_name | replace "." "-" }}-certificate
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.domain_name | replace "." "-" }}-tls
  issuerRef:
    name: {{ .Values.letsEncrypt.issuer }}
    kind: Issuer
  commonName: {{ .Values.domain_name }}
  dnsNames:
  - {{ .Values.domain_name }}
  - api.{{ .Values.domain_name }}
#  acme:
#    config:
#    - http01:
#        ingress: {{ .Values.ingress }}
#      domains:
#      - {{ .Values.domain_name }}
#      - api.{{ .Values.domain_name }}