apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bee-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bee-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bee-ui.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
#      serviceAccountName: {{ include "bee-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-nginx-config
            items:
            - key: conf-default.conf
              path: default.conf
      {{- if .Values.sslEncrypt }}
        - name: ssl-certs
          secret:
            secretName: {{ .Values.domain_name | replace "." "-" }}-tls
            items:
            - key: tls.crt
              path: cert.crt
            - key: tls.key
              path: cert.key
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
    {{- if .Values.sslEncrypt }}
            - name: https
              containerPort: 443
              protocol: TCP   
    {{- else }}
            - name: http
              containerPort: 80
              protocol: TCP   
    {{- end }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
    {{- if .Values.sslEncrypt }}
            - name: ssl-certs
              mountPath: /etc/certs
              readOnly: true
    {{- end }}
        {{- with .Values.env }}
          env:
        {{- toYaml . | nindent 12 }}
      {{- end }}
#    {{- if .Values.sslEncrypt }}    
#          livenessProbe:
#            httpGet:
#              path: /
#              port: https
#          readinessProbe:
#            httpGet:
#              path: /
#              port: https
#    {{- else }}
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#            port: http
#    {{- end }}    
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}