apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Name }}
  labels:
    {{- include "bee-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
  {{- toYaml . | nindent 4 }}
  {{- end }} 
  selector:
    {{- include "bee-ui.selectorLabels" . | nindent 4 }}
