apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  config.cfg: |-
{{- include "bee-api.config-file" . | nindent 4 }}
