{{- if not .Values.beeApi.persistence.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
data:
{{- if .Values.beeApi.database.username }}
  username: {{ .Values.beeApi.database.username | b64enc }}
{{- end }}
{{- if .Values.beeApi.database.password }}
  password: {{ .Values.beeApi.database.password | b64enc }}
{{- end }}
  port:  {{ .Values.beeApi.database.port | quote | b64enc }}
{{- if .Values.beeApi.database.host }}
  host: {{ .Values.beeApi.database.host | b64enc }}
{{- end }}
  databaseName: {{ .Values.beeApi.database.databaseName | b64enc }}
  type: {{ .Values.beeApi.database.type | b64enc }}
{{- end }}