{{- if not .Values.beeApi.persistence.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
data:
{{- with .Values.beeApi.database -}}
{{- if .username }}
  username: {{ .username | b64enc }}
{{- end }}
{{- if .password }}
  password: {{ .password | b64enc }}
{{- end }}
{{- if .port }}
  port:  {{ .port | quote | b64enc }}
{{- end }}
{{- if .host }}
  host: {{ .host | b64enc }}
{{- end }}
  databaseName: {{ .databaseName | b64enc }}
  type: {{ .type | b64enc }}
{{- end }}
{{- end }}
