{{- if .Values.cluster.issuer.name }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "{{ .Values.cluster.issuer.name }}-{{ .Values.cluster.issuer.environment }}-issuer"
  namespace: {{ .Release.Namespace }}
spec:
{{- if eq .Values.cluster.issuer.name "acme" }}
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ .Values.cluster.issuer.email }}
    server: https://acme-{{ .Values.cluster.issuer.environment }}-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: "{{ .Chart.Name }}-issuer-account-key"
    solvers:
    {{- toYaml .Values.cluster.issuer.solvers | nindent 6 }}
{{- end }}
{{- if eq .Values.cluster.issuer.name "self" }}
  selfSigned: {}
{{- end }}
{{- end }}