apiVersion: v2
name: bee-ui
description: Bee Web Frontend

type: application
icon: https://github.com/BeeRaspberry/assets/blob/master/images/beewhitecrosshatch.icon

version: 1.15.0
appVersion: 1.15.0
home: https://github.com/BeeRaspberry/helm-charts
sources:
  - https://github.com/BeeRaspberry/beeweb-ui

maintainers:
  - name: Peter White