apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bee-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.beeUi.replicaCount }}
  selector:
    matchLabels:
      {{- include "bee-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bee-web.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.beeUi.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bee-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.beeUi.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.beeUi.securityContext | nindent 12 }}
          image: "{{ .Values.beeUi.image.repository }}:{{ .Values.beeApi.image.version }}"
          imagePullPolicy: {{ .Values.beeUi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP   
        {{- with .Values.beeUi.env }}
          env:
        {{- toYaml . | nindent 12 }}
      {{- end }}    
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.beeUi.resources | nindent 12 }}
      {{- with .Values.beeUi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.beeUi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.beeUi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}