apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bee-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.beeUi.replicaCount }}
  selector:
    matchLabels:
      {{- include "bee-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bee-web.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.beeUi.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bee-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.beeUi.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.beeUi.securityContext | nindent 12 }}
          image: "{{ .Values.beeUi.image.repository }}:{{ .Values.beeApi.image.version }}"
          imagePullPolicy: {{ .Values.beeUi.image.pullPolicy }}
          ports:
    {{- range .Values.beeUi.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
    {{- end }}
          env:
            - name: API_URL
              value: "http://{{ .Chart.Name }}-api"
    {{- with .Values.beeUi.env }}
        {{- toYaml . | nindent 12 }}
    {{- end }}    
          livenessProbe:
            httpGet:
              path: /
    {{- with index .Values.beeUi.service.ports 0 }}
              port: {{ .targetPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .targetPort }}
    {{- end }}
          resources:
            {{- toYaml .Values.beeUi.resources | nindent 12 }}
      {{- with .Values.beeUi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.beeUi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.beeUi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}