apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bee-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.beeUi.service.type }}
  {{- with .Values.beeUi.service.ports }}
  ports:
  {{- toYaml . | nindent 4 }}
  {{- end }} 
  selector:
    {{- include "bee-web.selectorLabels" . | nindent 4 }}
