apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.{{ .Values.domain_name }}
    http:
      paths:
      - path: /
        backend:
          serviceName: bee-api
          servicePort: 80
  tls:
    - hosts:
        - api.{{ .Values.domain_name }}
      secretName: {{ .Values.domain_name | replace "." "-" }}-tls
