cluster:
  podsecuritypolicy:
    create: false
  rbac:
    create: true

beeApi:
  ReplicaCount: 1

  image:
    repository: beeraspberry/bee-api
    version: latest
    pullPolicy: Always

  imagePullSecrets: []

  database:
    port: "5432"
    username: beeapi
    password: "test"
    host: "test"
    databaseName: beeapi
    type: postgresql

  env:
    - name: DOMAIN_NAME
      value: example.com
    - name: PORT
      value: 8000

  nameOverride: ""
  fullnameOverride: ""

  persistence:
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
    storageClass:
    accessMode: ReadWriteOnce
    size: 8Gi
    annotations: {}

  serviceAccount:
  # Specifies whether a service account should be created
    create: true
  # Annotations to add to the service account
    annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
    name:

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  service:
    type: LoadBalancer
    ports:
    - name: http-bee-api
      port: 8080
      protocol: TCP
      targetPort: 8000

  ingress:
    enabled: false
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: map-example.local
        paths: []
    tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

  resources:
    limits:
      cpu: 0.5
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 50Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  frontend:
    enabled: false

  cluster-security:
    podsecuritypolicy:
      create: true

  bee-security:
    podsecuritypolicy:
      create: true

beeUi:
  replicaCount: 1
  image:
    repository: beeraspberry/bee-ui
    pullPolicy: Always
    version: latest
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
  # Specifies whether a service account should be created
    create: true
  # Annotations to add to the service account
    annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
    name:
  podSecurityContext: {}
  # fsGroup: 2000
  securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  #  runAsNonRoot: true
  #  runAsUser: 1000
  service:
    type: LoadBalancer
    ports:
    - name: http-bee-web
      port: 8090
      protocol: TCP
      targetPort: 8000
  ingress:
    enabled: true
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: map-example.local
        paths: []
    tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  resources:
    limits:
      cpu: 0.5
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 50Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  frontend:
    enabled: false
  backend_api:
    host: localhost
    port: "8000"
  # http or https
    protocol: http
  env:
    - name: DEBUG
      value: "false"
    - name: PRODUCTION
      value: "true"
    - name: PORT
      value: "8000"
    - name: DOMAIN_NAME
      value: example.com
