apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-config-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data: 
  config.cfg: |-
    {{ tpl (.Files.Get "config.conf") . | b64enc }}
  