apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-config-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData: 
  config.cfg: |-
    SQLALCHEMY_TRACK_MODIFICATIONS = {{ .Values.config.db.sqlalchemy_track_modifications }}
    APP_NAME = {{ .Values.config.general.app_name }}
    DEBUG = {{ .Values.config.general.debug }}
    TESTING = {{ .Values.config.general.testing }}
    {{- if eq .Values.database.type "sqlite" -}}
    SQLALCHEMY_DATABASE_URI = 'sqlite:///{{ .Values.db.filename }}'
    {{- else -}}
    SQLALCHEMY_DATABASE_URI = '{{ .Values.database.type }}://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.database }}'
    {{- end -}}
    BCRYPT_LOG_ROUNDS = {{ .Values.config.security.bcrypt_log_rounds }}
    SECURITY_PASSWORD_HASH = {{ .Values.config.security.password_hash }}
    SECURITY_PASSWORD_SALT = {{ .Values.config.security.password_salt }}
    SECURITY_TOKEN_AUTHENTICATION_KEY = {{ .Values.config.security.token_authentication_key }}
    SECURITY_TOKEN_AUTHENTICATION_HEADER = {{ .Values.config.security.token_authentication_header }}
    SECURITY_TOKEN_MAX_AGE = {{ .Values.config.security.token_max_age }}
    SECURITY_TRACKABLE = {{ .Values.config.security.trackable }}
    SECURITY_RECOVERABLE = {{ .Values.config.security.recoverable }}
    SECURITY_CONFIRMABLE = {{ .Values.config.security.confirmable }}
    SECURITY_REGISTERABLE = {{ .Values.config.security.registerable }}
    SECURITY_SEND_REGISTER_EMAIL = {{ .Values.config.security.send_register_email }}
    SECURITY_USER_IDENTITY_ATTRIBUTES = {{ .Values.config.security.user_identity_attributes }}
    SECURITY_LOGIN_URL = {{ .Values.config.security.login_url }}
    WTF_CSRF_ENABLED = {{ .Values.config.security.wtf_csrf_enabled }}
    MAIL_SERVER = {{ .Values.config.email.server }}
    MAIL_PORT = {{ .Values.config.email.port }}
    MAIL_USE_TLS = {{ .Values.config.email.use_tls }}
    MAIL_USE_SSL = {{ .Values.config.email.use_ssl }}
    MAIL_USERNAME = {{ .Values.config.email.username }}
    MAIL_PASSWORD = {{ .Values.config.email.password }}
    MAIL_DEFAULT_SENDER = {{ .Values.config.email.default_sender }}
    
    # Admin account
    ADMIN_PASSWORD = {{ .Values.config.admin.password }}
    ADMIN_EMAIL = {{ .Values.config.admin.email }}
    EMAIL_SUBJECT_PREFIX = '[{}]'.format(APP_NAME)
    EMAIL_SENDER = '{app_name} Admin <{email}>'.format(
        app_name=APP_NAME, email=MAIL_USERNAME)
    
    SOCIAL_GOOGLE = {
        'consumer_key': {{ .Values.config.social.google.key }},
        'consumer_secret': {{ .Values.config.social.google.secret }}
    }
    