{{- if and .Values.api.persistence.enabled (not .Values.api.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}-claim"
  namespace: {{ .Release.Name }}
{{- with .Values.api.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "bee-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.api.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.api.persistence.size | quote }}
  storageClassName: {{ .Values.api.persistence.storageClass | quote }}
{{- end }}