apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-volume
  labels:
    type: local
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  hostPath:
    path: "/mnt/data"
