apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bee-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bee-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bee-api.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
#      serviceAccountName: {{ include "bee-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      volumes:
        - name: "{{ .Chart.Name }}-config-volume"
          secret:
            secretName: "{{ .Release.Name }}-config-secret"
    {{- if .Values.persistence.enabled }}
        - name: "{{ .Chart.Name }}-data-volume"
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}-claim"
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: "{{ .Chart.Name }}-config-volume"
              mountPath: "/etc/bee-api/"
    {{- if .Values.persistence.enabled }}          
            - name: "{{ .Chart.Name }}-data-volume"
              mountPath: "/data"
    {{- end }}
          env:
           {{- toYaml .Values.env | nindent 12 }}     
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}