name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Get repo and owner
      uses: jungwinter/split@v1
      id: split
      with:
        msg: ${{ github.repository }}
        seperator: "/"

    - name: Lint Helm Main Chart
      uses: WyriHaximus/github-action-helm3@v1
      with:
        exec: helm lint .

    - name: Lint Helm bee-api Chart
      uses: WyriHaximus/github-action-helm3@v1
      with:
        exec: helm lint ./charts/bee-api


    - name: Lint Helm bee-web Chart
      uses: WyriHaximus/github-action-helm3@v1
      with:
        exec: helm lint ./charts/bee-web

    - name: Publish Bee api helm packages
      uses: helm/chart-releaser-action@v1.0.0-rc.1
      with:
        charts_dir: charts/bee-api
        charts_repo_url: https://${{ github.repository_owner }}.github.io/${{ steps.split.outputs._1 }}/helm-packages
      env:
        CR_TOKEN: ${{ secrets.PAGES_TOKEN }}

    - name: Publish Bee Web UI helm packages
      uses: helm/chart-releaser-action@v1.0.0-rc.1
      with:
        charts_dir: charts/beeweb-ui
        charts_repo_url: https://${{ github.repository_owner }}.github.io/${{ steps.split.outputs._1 }}/helm-packages
      env:
        CR_TOKEN: ${{ secrets.PAGES_TOKEN }}
