name: build-master

on: 
  push:
    branches:
      - master

# Job builds Helm packages when Chart.yml changes. Check required to keep package process from failing.
# Package creation only occurs on the 'master' branch.

# Auto-increments version info for each chart if developer forgets.
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Configure Job
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        echo ::set-env name=VERSION_CHANGE::0

    - name: Run chart-testing (lint)
      id: lint
      uses: helm/chart-testing-action@v1.0.0-rc.1
      with:
        command: lint
        config: .github/ct.yaml

    - name: Create kind cluster
      uses: helm/kind-action@v1.0.0-alpha.3
      # Only build a kind cluster if there are chart changes to test.
      if: steps.lint.outputs.changed == 'true'

    - name: Run chart-testing (install)
      uses: helm/chart-testing-action@v1.0.0-rc.1
      with:
        command: install
        
    - name: Get repo and owner
      uses: jungwinter/split@v1
      id: split
      with:
        msg: ${{ github.repository }}
        seperator: "/"
  
    - name: Check for change in charts/bee-web
      id: chart_change
      run: |
        echo "##[set-output name=change;]$(git diff HEAD^ HEAD charts/bee-web | wc -l)"
      
# Assume since the developer didn't change the version then this is a minor change.
# Increment by one, and set patch to 0.
    - name: Update version and AppVersion of Chart.yaml
      if: steps.chart_change.outputs.change > 0
      run: |
        IFS='.'; read -r -a array <<< "$(grep version: charts/bee-web/Chart.yaml |\
          head -1 | awk -F ': ' '{print $NF}')"
        CNT=$((${array[1]} + 1))
        sed -i "s/^version: .*/version: ${array[0]}.${CNT}.0/" charts/bee-web/Chart.yaml
        IFS='.'; read -r -a array <<< "$(grep appVersion: charts/bee-web/Chart.yaml |\
         awk -F ': ' '{print $NF}')"
        CNT=$((${array[1]} + 1))
        sed -i "s/^appVersion: .*/appVersion: ${array[0]}.${CNT}.0/" charts/bee-web/Chart.yaml
        git add charts/bee-web/Chart.yaml
        git commit -m "Updated dependencies in Chart.yaml"

    - name: Push changes to master
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true

    - name: Publish Bee Web helm packages
      uses: helm/chart-releaser-action@master
      with:
        charts_dir: ${{ github.repository }}
#        charts_repo_url: https://${{ github.repository_owner }}.github.io/${{ steps.split.outputs._1 }}/helm-packages
      env:
        CR_TOKEN: ${{ secrets.PAGES_TOKEN }}
