name: build

on: 
  push:
    branches:
      - master

# Job builds Helm packages when Chart.yml changes. Check required to keep package process from failing.
# Package creation only occurs on the 'master' branch.
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Configure Job
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        echo ::set-env name=VERSION_CHANGE::0
        echo ::set-env name=API_VERSION_CHANGE::0
        echo ::set-env name=UI_VERSION_CHANGE::0

    - name: Get repo and owner
      uses: jungwinter/split@v1
      id: split
      with:
        msg: ${{ github.repository }}
        seperator: "/"
  
    - name: Check Version change - charts/bee-api
      run: |
        DIFF=$(git diff HEAD^ HEAD charts/bee-api/Chart.yaml)
        if [[ ! -z "$DIFF" ]]; then
          echo ::set-env name=VERSION_CHANGE::1
          echo ::set-env name=API_VERSION_CHANGE::1
        fi

    - name: Check Version change - charts/bee-ui
      run: |
        DIFF=$(git diff HEAD^ HEAD charts/bee-ui/Chart.yaml)
        if [[ ! -z "$DIFF" ]]; then
          cat charts/bee-ui/Chart.yaml
          echo ::set-env name=VERSION_CHANGE::1
          echo ::set-env name=UI_VERSION_CHANGE::1
        fi

    - name: Update dependency version of bee-api
      if: env.API_VERSION_CHANGE == 1
      run: |
        VERSION=$(grep appVersion: charts/bee-api/Chart.yaml | awk -F ': ' '{print $NF}')
        printf "/- name: bee-api/" >sed-command
        printf '!b;n;c\ \ version: "' >>sed-command
        printf "${VERSION}"\" >>sed-command
        sed -f sed-command Chart.yaml

    - name: Update dependency version of bee-ui
      if: env.UI_VERSION_CHANGE == 1
      run: |
        grep appVersion: charts/bee-ui/Chart.yaml | awk -F ': ' '{print $NF}'
        printf "/- name: bee-ui/" >sed-command
        printf '!b;n;c\ \ version: "' >>sed-command
        printf "${VERSION}"\" >>sed-command
        sed -f sed-command Chart.yaml

# Assume since the developer didn't change the version then this is a minor change.
# Increment by one, and set patch to 0.
    - name: Update version and AppVersion of Chart.yaml
      if: env.VERSION_CHANGE == 1
      run: |
        IFS='.'; read -r -a array <<< "$(grep version: Chart.yaml | head -1 | awk -F ': ' '{print $NF}')"
        CNT=$((${array[1]} + 1))
        sed -i "s/^version: .*/version: ${array[0]}.${CNT}.0/" Chart.yaml
        IFS='.'; read -r -a array <<< "$(grep appVersion: Chart.yaml | awk -F ': ' '{print $NF}')"
        CNT=$((${array[1]} + 1))
        sed -i "s/^appVersion: .*/appVersion: ${array[0]}.${CNT}.0/" Chart.yaml
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --local user.name ${GITHUB_ACTOR}
        git add Chart.yaml
        git commit -m "Updated dependencies in Chart.yaml"

    - name: Push changes to master
      if: env.VERSION_CHANGE == 1
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true

    - name: Publish Bee api helm packages
      if: env.API_VERSION_CHANGE == 1 
      uses: helm/chart-releaser-action@v1.0.0-rc.2
      with:
        charts_dir: charts/bee-api
        charts_repo_url: https://${{ github.repository_owner }}.github.io/${{ steps.split.outputs._1 }}/helm-packages
      env:
        CR_TOKEN: ${{ secrets.PAGES_TOKEN }}

    - name: Publish Bee Web UI helm packages
      if: env.UI_VERSION_CHANGE == 1
      uses: helm/chart-releaser-action@v1.0.0-rc.2
      with:
        charts_dir: charts/bee-ui
        charts_repo_url: https://${{ github.repository_owner }}.github.io/${{ steps.split.outputs._1 }}/helm-packages
      env:
        CR_TOKEN: ${{ secrets.PAGES_TOKEN }}